# Generated by Django 5.0.6 on 2024-06-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=models.CharField(max_length=240),
        ),
    ]
